## -*- encoding: utf-8 -*-
## This file (Coursework.sagetex.sage) was *autogenerated* from Coursework.tex with sagetex.sty version 2012/01/16 v2.3.3-69dcb0eb93de.
import sagetex
_st_ = sagetex.SageTeXProcessor('Coursework', version='2012/01/16 v2.3.3-69dcb0eb93de', version_check=True)
_st_.blockbegin()
try:
     f(x) = exp(x) * sin(2*x)
except:
 _st_.goboom(20)
_st_.blockend()
_st_.endofdoc()
